#!/bin/bash
ROS_ETHERCAT_LOOP_SOURCE="$(catkin_find --libexec ros_ethercat_loop)/ros_ethercat_loop"
if [ -x "$ROS_ETHERCAT_LOOP_SOURCE" ]; then
    sudo setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip $ROS_ETHERCAT_LOOP_SOURCE
    sudo setcap cap_sys_nice=eip /usr/bin/nice
fi

ROS_ETHERCAT_LOOP_BIN="$(catkin_find --bin)/ros_ethercat_loop"
if [ -x "$ROS_ETHERCAT_LOOP_BIN" ]; then
    sudo setcap cap_sys_nice,cap_ipc_lock,cap_net_raw,cap_net_admin=eip $ROS_ETHERCAT_LOOP_BIN
    sudo setcap cap_sys_nice=eip /usr/bin/nice
fi

